package view.servidor;

import controller.EstacaoJpaController;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.swing.table.DefaultTableModel;
import model.Estacao;
import persistence.PersistenceSingleton;
import util.Tabela;

public class ListaEstacoes extends javax.swing.JPanel {

    TelaPrincipal telaPrincipal;

    public ListaEstacoes(TelaPrincipal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;

        EntityManagerFactory emf = PersistenceSingleton.getInstance().getEntityManagerFactory();
        EstacaoJpaController ejc = new EstacaoJpaController(emf);

        DefaultTableModel dtm = (DefaultTableModel) tableEstacoes.getModel();

        List<Estacao> lista = ejc.findEstacaoEntities();

        Tabela.limparTabela(dtm);
        
        for (Estacao estacao : lista) {
            String nome, ip;
            long memoriaDisponivel;

            nome = estacao.getNome();
            ip = estacao.getIpv4();
            memoriaDisponivel = estacao.getMemoriaDisponivel();

            dtm.addRow(new String[]{nome, ip, String.valueOf(memoriaDisponivel/1000000) + " MB", ""});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEstacoes = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(678, 476));

        tableEstacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "IP", "Memória Disponível", "Informações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEstacoes.getTableHeader().setReorderingAllowed(false);
        tableEstacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEstacoesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEstacoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableEstacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEstacoesMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tableEstacoes.getModel();
        int linhaSelecionada = tableEstacoes.getSelectedRow();

        telaPrincipal.mostraProcessos(dtm.getValueAt(linhaSelecionada, 0).toString());
    }//GEN-LAST:event_tableEstacoesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEstacoes;
    // End of variables declaration//GEN-END:variables
}
